language: java
sudo: false #faster builds

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
#  - ./gradlew stage

cache:
  directories:
    - $HOME/.m2

after_success:
    - bash <(curl -s https://codecov.io/bash) -t b0efbf49-50f2-47a7-afce-04a13f230af7